// examples/child-nuxt/app/components/Navigation.vue
<template>
  <div class="h-16 px-4 py-2">
    <nav class="grid grid-cols-3 gap 4 items-center h-full">
      <h2>Navigation Component</h2>
      <ul class="flex justify-center gap-6">
        <li v-for="item in navigationItems" :key="item.link">
          <a :href="item.link">{{ item.name }}</a>
        </li>
      </ul>
    </nav>
  </div>
</template>

<script setup lang="tsx">
const navigationItems = [
  { name: "Home", link: "/" },
  { name: "Child-Next", link: "/child-next" },
  { name: "Child-Nuxt", link: "/child-nuxt/home" },
];
</script>

// examples/host-app/components/Navigation/index.tsx
const navigationButtons = [
  { name: "Home", link: "/" },
  { name: "Child-Next", link: "/child-next" },
  { name: "Child-Nuxt", link: "/child-nuxt" },
];

const Navigation = () => {
  return (
    <div className="h-16 px-4 py-2">
      <div className="grid grid-cols-3 gap-4 flex items-center h-full">
        <h2>Navigation Component</h2>
        <div className="flex justify-center gap-6">
          {navigationButtons.map((button) => (
            <a key={button.name} href={button.link}>
              {button.name}
            </a>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Navigation;
